app/models/line_item.rb, app/models/producer.rb, app/models/product.rb, app/models/shopping_cart.rb, app/models/tag.rb, app/models/tagging.rb
=> added validations and associations

app/views/producers/index.html.erb, config/routes.rb
=> Create index view

.gitignore, app/javascript/packs/application.js, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
linked each category card to the producers index page
=> Linkingcategorycards

app/controllers/pages_controller.rb, app/controllers/producers_controller.rb, app/views/pages/new_producer.html.erb, app/views/producers/new.html.erb, config/routes.rb
- created welcome page for new producers
- created producers/new path with controller & view
=> ARCH: producer signup welcome page and producer new page

app/controllers/pages_controller.rb, app/controllers/producers_controller.rb, app/javascript/packs/application.js, app/views/pages/producer_confirmation.html.erb
- business confirmation page redirects to dashboard when it's verified
=> FEAT: new producer approval page redirects when business is verified

app/controllers/application_controller.rb, app/controllers/products_controller.rb, app/views/products/new.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
- Add a new product from dashboard
- Add  a new product from navbar if logged in as a producer
=> New product

app/views/producers/index.html.erb, db/seeds.rb
- tag elements don't duplicate on index producer cards any more
=> FIX: when searching for tags they are no longer duplicated

app/controllers/orders_controller.rb, app/controllers/producers_controller.rb, app/javascript/components/init_producer_map.js, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/shopping_cart.rb, app/views/orders/show.html.erb, app/views/producers/show.html.erb
producer show page map with markers works.
custom message on order page.
=> Producer map + no producer duplicates displayed on Order show pg

app/controllers/products_controller.rb, app/controllers/tagging_controller.rb, app/controllers/taggings_controller.rb, app/models/product.rb, app/models/tag.rb, app/models/tagging.rb, app/views/dashboard/index.html.erb, app/views/products/new.html.erb, app/views/taggings/new.html.erb, config/routes.rb, db/seeds.rb, test/controllers/tagging_controller_test.rb
- can add tags to products, but only after product was created
=> Adding product tags

app/assets/stylesheets/pages/_shoppingcart_show.scss, app/controllers/shopping_cart/line_items_controller.rb, app/views/shopping_carts/show.html.erb, config/routes.rb
=> Qty items cart

app/assets/stylesheets/pages/_show.scss, app/views/pages/home.html.erb, app/views/producers/show.html.erb, db/seeds.rb
change in seeds + few front end changes
=> Show page front

app/controllers/products_controller.rb, app/javascript/components/change_cart_qty.js, app/models/product.rb, app/views/dashboard/index.html.erb, app/views/products/edit.html.erb, app/views/products/new.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
- Producer dashboard: can edit and delete products
- Producer dashboard: when adding a new product can add tags now
- FIX: navbar 'add product' now redirects to add product page (instead of shopping cart)
=> Dashboard crud

app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_shoppingcart_show.scss, app/controllers/shopping_cart/line_items_controller.rb, app/javascript/components/change_cart_qty.js, app/javascript/packs/application.js, app/javascript/plugins/banner.js, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/shopping_carts/show.html.erb, config/routes.rb, package.json, yarn.lock
Feat: change qty of line item in shopping cart with JS
replace the sopping cart with a bag
some frontend on shopping cart
=> Add items bug

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_checkout.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/orders_controller.rb, app/models/shopping_cart.rb, app/views/orders/show.html.erb, app/views/pages/new_producer.html.erb, app/views/payments/new.html.erb
Few stylings for logo, order page
=> Styling order page

app/views/pages/home.html.erb, app/views/producers/index.html.erb
Disabled turbolinks from CTA button from home page and for each producer card.
=> BUG: Disabled turbolinks to fix map bug

app/assets/stylesheets/components/_checkmark-animated.scss, app/assets/stylesheets/components/_index.scss, app/controllers/producers_controller.rb, app/views/pages/producer_confirmation.html.erb, app/views/producers/new.html.erb
- Animated checkmark shows up when a new business signs up
=> FEAT: Animated checkmark when business details are submitted

app/assets/stylesheets/config/_colors.scss, app/controllers/shopping_cart/line_items_controller.rb, app/models/producer.rb, app/views/pages/home.html.erb, app/views/producers/_info_window.html.erb
solved bug with JS on the items
=> solved js porblem cart

app/assets/stylesheets/components/_overlay.scss
- overlay sits on top of all elements now (some used to peek through)
=> FIX: Changed overlay z index so it sits on top of all elements now.

app/assets/stylesheets/components/_badge.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/controllers/shopping_cart/line_items_controller.rb
=> solved js map

app/models/user.rb, db/schema.rb, db/seeds.rb
=> Seeds fixing

app/assets/stylesheets/components/_card.scss, app/controllers/application_controller.rb, app/models/user.rb, app/views/producers/index.html.erb
=> Index cards

app/assets/stylesheets/config/_colors.scss, db/schema.rb
=> Seed bugfix

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_landing-card.scss, app/views/pages/home.html.erb
- swipeable category cards on the landing page with some styling
=> Landing cards

app/controllers/application_controller.rb, app/mailers/user_mailer.rb, app/models/producer.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, config/initializers/devise.rb
=> mail solved

app/assets/stylesheets/components/_map.scss, app/controllers/application_controller.rb, app/controllers/producers_controller.rb, app/javascript/plugins/init_mapbox.js, app/models/user.rb
Accessed photo vs producers controller using
url_for(producer.photo) rather than mapbox's asset_url helper.
=> Avatar markers on map for producer index page

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> navbar improved

app/models/tag.rb, app/views/pages/home.html.erb, db/seeds.rb
- added photos to tags on landing page
=> Adding tag photos

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_toggle.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/producers_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/devise/registrations/new.html.erb, app/views/producers/index.html.erb, app/views/producers/show.html.erb, app/views/shared/_navbar.html.erb
FEAT: frontend index, maps, froentend show page (still product carousel to do)
=> Frontend show

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_show.scss, app/javascript/components/aos.js, app/javascript/packs/application.js, app/views/producers/index.html.erb, app/views/producers/show.html.erb, package.json, yarn.lock
Feat: AOS animation on index
show page : starting products page
=> Front index and products

app/controllers/application_controller.rb, app/controllers/shopping_cart/line_items_controller.rb, app/controllers/shopping_carts_controller.rb, app/models/user.rb, app/views/orders/show.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb
Feat: shopping_cart after login only in order to solve the seeds issue
=> Feat: shopping_cart after login

app/views/orders/show.html.erb, app/views/user_mailer/welcome.html.erb, config/environments/development.rb, db/schema.rb, lib/tasks/dev.rake
To open email in a browser:
In the terminal run: 
`rails dev:send_test_welcome_mail`
=> Email styling complete

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_index.scss, app/views/dashboard/index.html.erb, db/seeds.rb
- progress with dashboard styling
=> Dashboard styling v2

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_badge.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_overlay.scss, app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_shoppingcart_show.scss, app/assets/stylesheets/pages/_show.scss, app/views/dashboard/index.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/shopping_carts/show.html.erb, db/schema.rb
- Various bug fixes
- Added avatar to producer dashboard
=> Frontend fixes

app/assets/stylesheets/components/_checkmark-animated.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_new_producer.scss, app/views/pages/producer_confirmation.html.erb
- producer confirmation page styling
=> Frontend styling

app/assets/stylesheets/components/_badge.scss, app/assets/stylesheets/config/_colors.scss, app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/views/producers/index.html.erb, app/views/producers/new.html.erb
- moved tags on index card to top right corner
=> Frontend styling v2
